# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from waypoint_planning/Replan_Msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import waypoint_planning.msg

class Replan_Msg(genpy.Message):
  _md5sum = "ba579b4b1534fcbd7ed9e29ed0638bff"
  _type = "waypoint_planning/Replan_Msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 uav_id
waypoint_planning/Coordinates coordinates
================================================================================
MSG: waypoint_planning/Coordinates
float64 longitude
float64 latitude
"""
  __slots__ = ['uav_id','coordinates']
  _slot_types = ['int8','waypoint_planning/Coordinates']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       uav_id,coordinates

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Replan_Msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.uav_id is None:
        self.uav_id = 0
      if self.coordinates is None:
        self.coordinates = waypoint_planning.msg.Coordinates()
    else:
      self.uav_id = 0
      self.coordinates = waypoint_planning.msg.Coordinates()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_b2d.pack(_x.uav_id, _x.coordinates.longitude, _x.coordinates.latitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.coordinates is None:
        self.coordinates = waypoint_planning.msg.Coordinates()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.uav_id, _x.coordinates.longitude, _x.coordinates.latitude,) = _struct_b2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_b2d.pack(_x.uav_id, _x.coordinates.longitude, _x.coordinates.latitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.coordinates is None:
        self.coordinates = waypoint_planning.msg.Coordinates()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.uav_id, _x.coordinates.longitude, _x.coordinates.latitude,) = _struct_b2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_b2d = struct.Struct("<b2d")
