// Generated by gencpp from file waypoint_planning/Coordinates.msg
// DO NOT EDIT!


#ifndef WAYPOINT_PLANNING_MESSAGE_COORDINATES_H
#define WAYPOINT_PLANNING_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_planning
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : longitude(0.0)
    , latitude(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)  {
    }



   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;




  typedef boost::shared_ptr< ::waypoint_planning::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_planning::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::waypoint_planning::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::waypoint_planning::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::waypoint_planning::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_planning::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_planning::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'waypoint_planning': ['/home/fotis/Dev/Workspaces/ROS/bluebox_path_planning/src/waypoint_planning/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_planning::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_planning::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_planning::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_planning::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_planning::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_planning::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_planning::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd6c3d0b911e124b1f0b5a2ade9c1a01";
  }

  static const char* value(const ::waypoint_planning::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd6c3d0b911e124bULL;
  static const uint64_t static_value2 = 0x1f0b5a2ade9c1a01ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_planning::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_planning/Coordinates";
  }

  static const char* value(const ::waypoint_planning::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_planning::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 longitude\n\
float64 latitude\n\
";
  }

  static const char* value(const ::waypoint_planning::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_planning::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_planning::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_planning::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_PLANNING_MESSAGE_COORDINATES_H
